import { Prisma } from '@prisma/client';
import prisma from './prisma';

export const initializeUserDataIfNecessary = async (
  email: string
): Promise<void> => {
  const user = await prisma.user.findUnique({
    where: {
      email,
    },
  });
  if (!!user) {
    return;
  }
  await prisma.user.create({
    data: {
      email,
      exercises: {
        create: DEFAULT_EXERCISES,
      },
    },
  });
};

const DEFAULT_EXERCISES: Prisma.ExerciseCreateWithoutUserInput[] = [
  {
    name: 'Barbell Bench Press',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Incline Barbell Bench Press',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Decline Barbell Bench Press',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Dumbbell Bench Press',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Dumbbell Fly',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders'],
    exerciseType: 'weighted',
  },
  {
    name: 'Incline Dumbbell Bench Press',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Incline Dumbbell Fly',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders'],
    exerciseType: 'weighted',
  },
  {
    name: 'Decline Dumbbell Fly',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders'],
    exerciseType: 'weighted',
  },
  {
    name: 'Smith Machine Bench Press',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Smith Machine Incline Bench Press',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'High Cable Fly',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders'],
    exerciseType: 'weighted',
  },
  {
    name: 'Medium Cable Fly',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders'],
    exerciseType: 'weighted',
  },
  {
    name: 'Low Cable Fly',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders'],
    exerciseType: 'weighted',
  },
  {
    name: 'Plate Loaded Chest Press Machine',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Plate Loaded Inline Chest Press Machine',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Selector Chest Press Machine',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Chest Fly Machine',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders'],
    exerciseType: 'weighted',
  },
  {
    name: 'Dips',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'rep_based',
  },
  {
    name: 'Weighted Dips',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Machine-Supported Dips',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['shoulders', 'triceps'],
    exerciseType: 'assisted',
  },
  {
    name: 'Overhand Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Weighted Overhand Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Wide Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Weighted Wide Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Neutral Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Weighted Neutral Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Underhand Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Weighted Underhand Grip Pull Ups',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Machine-Supported Pull Ups - Overhand Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Machine-Supported Pull Ups - Wide Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Machine-Supported Pull Ups - Neutral Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Overhand Grip Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Wide Grip Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Neutral Grip Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Underhand Grip Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Behind The Neck Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['traps', 'biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Lat Pulldown - Single Arm',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Overhand Grip Plate Loaded Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Neutral Grip Plate Loaded Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Underhand Grip Plate Loaded Lat Pulldown',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Neutral Grip Plate Loaded Lat Pulldown - Single Arm',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Underhand Grip Plate Loaded Lat Pulldown - Single Arm',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Seated Cable Row - Overhand Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Seated Cable Row - Underhand Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Seated Cable Row - Neutral Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Seated Cable Row - Wide Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Seated Cable Row - Single Arm',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Bent-Over Barbell Row - Overhand Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['lower_back', 'biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Bent-Over Barbell Row - Underhand Grip',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['lower_back', 'biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'TBar Row',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['lower_back', 'biceps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Single-Arm Dumbbell Row',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'obliques'],
    exerciseType: 'weighted',
  },
  {
    name: 'Standing Cable Pullover',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['triceps', 'chest'],
    exerciseType: 'weighted',
  },
  {
    name: 'Standing Cable Pullover - Single Arm',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['triceps', 'chest'],
    exerciseType: 'weighted',
  },
  {
    name: 'Flat Dumbbell Pullover',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['triceps', 'chest'],
    exerciseType: 'weighted',
  },
  {
    name: 'Decline Dumbbell Pullover',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['triceps', 'chest'],
    exerciseType: 'weighted',
  },
  {
    name: 'Selector Chest Supported Row Machine',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Seated Dumbbell Overhead Press',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Seated Dumbbell Overhead Press - Single Arm',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Standing Barbell Overhead Press',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Standing Barbell Behind The Neck Press',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Smith Machine Overhead Press',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Smith Machine Behind The Neck Press',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Plate Loaded Machine Overhead Press',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Plate Loaded Machine Overhead Press - Single Arm',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Selector Overhead Press Machine',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Barbell Upright Row',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'EZ Bar Upright Row',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Cable Upright Row',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['biceps', 'traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Dumbbell Lateral Raise',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Single Arm Cable Lateral Raise',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Rear Delt Machine',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['traps'],
    exerciseType: 'weighted',
  },
  {
    name: 'Dumbbell Bent Over Reverse Fly',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['traps'],
  },
  {
    name: 'Dumbbell Incline Prone Reverse Fly',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['traps'],
  },
  {
    name: 'Single Arm Cable Reverse Fly',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['traps'],
  },
  {
    name: 'Cable Face Pull',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['traps', 'biceps'],
  },
  {
    name: 'EZ Bar Standing Barbell Curl - Narrow Grip',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'EZ Bar Standing Barbell Curl - Wide Grip',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Barbell Curl',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Barbell Curl - Overhand Grip',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'EZ Bar Preacher Curl',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Dumbbell Curl',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Dumbbell Hammer Curl',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Concentration Curl',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Standing Cable Curl',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Standing Cable Hammer Curl',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Standing Cable Hammer Curl - Overhand Grip',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Standing Cable Curl - Single Hand',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Standing Cable Hammer Curl - Single Hand',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Standing Cable Tricep Pushdown - Rope',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Standing Cable Tricep Pushdown - Straight Bar',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Standing Cable Tricep Pushdown - Single Arm',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Standing Cable Overhead Tricep Extension - Rope',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Standing Cable Overhead Tricep Extension - Straight Bar',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Cable Tricep Kick Bar - Single Arm',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Dumbbell Overhead Tricep Extensions',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Dumbbell Skull Crusher',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Dumbbell Skull Crusher - Behind Head',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Dumbbell Skull Crusher - Single Arm',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Prone Tricep Kick Back - Single Arm',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'EZ Bar Skull Crusher',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'EZ Bar Skull Crusher - Behind Head',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'H Bar Skull Crusher',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'H Bar Skull Crusher - Behind Head',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Triceps Press Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'triceps',
  },
  {
    name: 'Bench Dips',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'triceps',
    secondaryMuscleGroups: ['shoulders'],
  },
  {
    name: 'Crunches',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Situps',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Situps - Weighted',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Decline Crunches',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Decline Situps',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Decline Situps - Weighted',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'V Ups',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Lying Leg Raise',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Lying Leg Raise - Weighted',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Lying Reverse Crunch Up',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Hanging Knee Raise',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Hanging Knee Raise - Weighted',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Hanging Leg Raise',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Hanging Leg Raise - Weighted',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Hanging Knee Raise, Ab Station',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Hanging Leg Raise, Ab Station',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
    secondaryMuscleGroups: ['forearms'],
  },
  {
    name: 'Ab Machine',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Plank',
    exerciseType: 'timed',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Hollow',
    exerciseType: 'timed',
    primaryMuscleGroup: 'abs',
  },
  {
    name: 'Kneeling Ab Wheel',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'abs',
    secondaryMuscleGroups: ['lats'],
  },
  {
    name: 'Russian Twist',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'obliques',
  },
  {
    name: 'Decline Russian Twist',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'obliques',
  },
  {
    name: 'Side Plank',
    exerciseType: 'timed',
    primaryMuscleGroup: 'obliques',
  },
  {
    name: 'Hanging Leg Raise, Windshield Wipers',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'obliques',
  },
  {
    name: 'Standing Dumbbell Side Bend',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'obliques',
  },
  {
    name: 'Standing Dumbbell Shrugs',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'traps',
  },
  {
    name: 'Incline Prone Dumbbell Shrugs',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'traps',
  },
  {
    name: 'Barbell Back Squat',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Barbell Front Squat',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Barbell Lunge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Front Barbell Lunge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Goblet Squat',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Goblet Lunge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Goblet Bulgarian Lunge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Dumbbell Lunge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Dumbbell Walking Lunges',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Dumbbell Step Up',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Dumbbell Bulgarian Lunge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Smith Machine Squat',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Smith Machine Lunge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Leg Press',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Single Leg Press',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Hack Squat',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
    secondaryMuscleGroups: ['glutes', 'adductors'],
  },
  {
    name: 'Leg Extension',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
  },
  {
    name: 'Single Leg Extension',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'quads',
  },
  {
    name: 'Barbell Deadlift',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    name: 'Lying Leg Curl Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    name: 'Lying Single Leg Curl Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    name: 'Seated Leg Curl Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    name: 'Seated Single Leg Curl Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'hamstrings',
  },
  {
    name: 'Roman Chair Back Extension',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'hamstrings',
    secondaryMuscleGroups: ['glutes', 'lower_back'],
  },
  {
    name: 'Roman Chair Single Leg Back Extension',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'hamstrings',
    secondaryMuscleGroups: ['glutes', 'lower_back'],
  },
  {
    name: 'Barbell Hip Thrust',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'glutes',
    secondaryMuscleGroups: ['hamstrings'],
  },
  {
    name: 'Barbell Glute Bridge',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'glutes',
    secondaryMuscleGroups: ['hamstrings'],
  },
  {
    name: 'Leg Spread Abduction Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'abductors',
  },
  {
    name: 'Leg Close Adduction Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'adductors',
  },
  {
    name: 'Standing Calf Raise',
    exerciseType: 'rep_based',
    primaryMuscleGroup: 'calves',
  },
  {
    name: 'Standing Calf Raise - Weighted',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'calves',
  },
  {
    name: 'Calf Raise Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'calves',
  },
  {
    name: 'Seated Calf Raise Machine',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'calves',
  },
  {
    name: 'Calf Raise On Leg Press',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'calves',
  },
  {
    name: 'Calf Raise On Leg Press - Single Leg',
    exerciseType: 'weighted',
    primaryMuscleGroup: 'calves',
  },
  {
    name: 'Running',
    exerciseType: 'timed',
    primaryMuscleGroup: 'cardio',
  },
  {
    name: 'Bicycle Machine',
    exerciseType: 'timed',
    primaryMuscleGroup: 'cardio',
  },
  {
    name: 'Eliptical Machine',
    exerciseType: 'timed',
    primaryMuscleGroup: 'cardio',
  },
  {
    name: 'Step Machine',
    exerciseType: 'timed',
    primaryMuscleGroup: 'cardio',
  },
  {
    name: 'Jumping Rope',
    exerciseType: 'timed',
    primaryMuscleGroup: 'cardio',
  },
  {
    name: 'Mountain Climbers',
    exerciseType: 'timed',
    primaryMuscleGroup: 'cardio',
  },
  {
    name: 'Battling Rope',
    exerciseType: 'timed',
    primaryMuscleGroup: 'cardio',
  },
];
